### ISSUE TITLE
Add a heart icon which will animate and create in a very interactive way u can see it once

### ISSUE THREAD

**Issue by SahilShaw2004** [Shubhem/Profile_Card#1]

**Comment by Shubhem** [comment]
If someone raised an issue in your repository and you want to ask them to attach a pull request, you can politely comment on the issue, explaining how they can create a pull request. Here’s how you could phrase your response:

Comment on Issue:

Hi SahilShaw2004 ,

Thank you for raising the issue about adding a heart icon with an interactive animation to the profile card. This is a great suggestion, and I'd love to see it implemented!

**Comment by Abhiraj-Sardar** [comment]
@Shubhem 
can you assign this task to me?

**Comment by Abhiraj-Sardar** [comment]
and please include the label of hacktoberfest2024 to this issue.

**Comment by SahilShaw2004** [comment]
@Shubhem sorry.should i start doing the task?

**Comment by SahilShaw2004** [comment]
https://github.com/user-attachments/assets/15651a19-b5ff-4d3e-9367-664c53b2f9b9

This is the work which i was talking about
should i do it ?

**Comment by SahilShaw2004** [comment]
I created a PR and submitted already could you please add a label for hacktoberfest.Thank You!

**Comment by SahilShaw2004** [comment]
You didn't add label for hacktoberfest @Shubhem
