### ISSUE TITLE
Clicking on Gmail Icon Does Not Open Compose Window with Pre-filled Email

### ISSUE THREAD

**Issue by ohmschrodinger** [Shubhem/Profile_Card#4]
Currently, clicking on the Gmail icon in the profile card redirects the user to Gmail.com, but it does not open the compose window with the person's email pre-filled. Additionally, the email address of the person is not provided to users, making it impossible for users to contact the person via email
Suggested Improvement: The Gmail icon should be updated so that when clicked, it opens the compose email window directly in Gmail with the person's email pre-filled.

**Comment by Shubhem** [comment]
assigned and added the tag for hacktoberfest. Also, accepted your PR as well. kudos , done good work!!
